# MÓDULO 3 - JUPYTER NOTEBOOK 2

# Aula 5 - Pacotes e NumPy

## 1.1 Carregando módulos ``import``


In [1]:
import math
math.cos(math.pi)

-1.0

In [2]:
import numpy as np
np.cos(np.pi)

-1.0

In [3]:
from math import cos, pi
cos(pi)

-1.0

In [4]:
from math import *
sin(pi) ** 2 + cos(pi) ** 2

1.0

In [5]:
from numpy import *

Quando usamos o ``import *`` ele substitui todas as funções padrões do python pelas funções do módulo carregado, o que pode gerar um comportamento não esperado. Esse último comando ``from numpy import *`` substitui a função ``sum`` pela função ``numpy.sum`` e existe diferenças entre elas. Por isso o ``import *`` deve ser evitado.

## 1.2 Bibliotecas padrão do Python

Documentação das bibliotecas padrão do Python: https://docs.python.org/pt-br/3/library/.

## 1.3 Instalando e importando módulos de terceiros

Os módulos que não são padrão do Python podem ser usados da mesma forma que os módulos padrão, mas antes disso devem ser instalados na nossa máquina.

Para isso, podemos utilizar o seguinte comando no CMD:
``` 
$ pip install nome_do_pacote
```
``pip`` é um comando que automaticamente baixa e instala os pacotes listados no PyPI (*Python Package Index*), que contém um repositório de módulos.  

Após a instalação do módulo, a utilização dentro do jupyter notebook é igual ao das bibliotecas padrão usando o ``import``

Para mais informações sobre o PyPI, acesse o site: http://pypi.python.org/.

## 2.0 NumPy

Exemplo e texto adaptado de: https://numpy.org/

NumPy é o pacote essencial para computação científica em Python. É uma biblioteca Python que fornece um objeto array multidimensional (vetores e matrizes) e uma variedade de rotinas para operações rápidas.

A principal parte do pacote NumPy é o objeto NDArray, que é um conjunto de dados n-dimensional de tipos iguais. Possui um desempenho superior se comparado às sequencias padrão do Python (lista, tupla, etc), pois as operações são realizadas em códigos compilados. Outras diferenças são:

Os arrays NumPy são de tamanho fixo e as listas não. 

Os elementos dos arrays NumPy devem ser todos do mesmo tipo e na lista podem ter tipos diferentes.

Os arrays NumPy facilitam operações matemáticas em uma grande quantidade de dados. Normalmente, essas operações são executadas de forma mais eficiente e com menos código do que é possível usando as sequências do Python.

**Exemplo simples**

**Usando listas:**

In [6]:
lst_a = [1, 2, 3, 4, 5]
lst_b = [6, 7, 8, 9, 10]

In [7]:
lst_c = []
for i in range(len(lst_a)):
    lst_c.append(lst_a[i]*lst_b[i])
lst_c

[6, 14, 24, 36, 50]

**Usando NumPy:**

In [8]:
array_a = np.array([1, 2, 3, 4, 5])
array_b = np.array([6, 7, 8, 9, 10])
array_a, array_b

(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [9]:
array_c = array_a * array_b
array_a, array_b, array_c

(array([1, 2, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10]),
 array([ 6, 14, 24, 36, 50]))

___

# Aula 6 - NDArrays (*N-dimensional array*)

## 1.0 Criando NDarrays

### 1.1 A partir de listas do Python ``np.array``


In [10]:
np.array([5, 2, 3, 4, 1])

array([5, 2, 3, 4, 1])

In [11]:
# só aceita um tipo de dado, se houver diferentes tipos, é transformado em apenas 1.
np.array([5, 2, 3, 4, 1.0])
# np.array([5, 2, 3, 4, '1'])


array([5., 2., 3., 4., 1.])

In [12]:
#podemos explicitar o tipo de dado na construção.
np.array([5, 2, 3, 4, 1], dtype='float32')

array([5., 2., 3., 4., 1.], dtype=float32)

### 1.2 A partir de rotinas do NumPy ``np.zeros`` ``np.ones`` ``np.arrange`` ``np.random.randint``

Nas aulas anteriores, para criarmos grandes listas do Python (todos os números pares até o 200), usamos as estruturas de repetição ``while`` e ``for``. 

Para criar grandes arrays podemos usar rotinas do NumPy.

In [13]:
#criando um vetor de zeros
vetor_zeros = np.zeros(5)
vetor_zeros

array([0., 0., 0., 0., 0.])

In [14]:
#criando uma matriz de zeros
matriz_zeros = np.zeros((2, 5))
matriz_zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
#criando array dos numeros pares
pares = np.arange(2, 201, 2)
pares

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198, 200])

In [16]:
np.random.rand(3,2)

array([[0.65749797, 0.78507999],
       [0.18393481, 0.60624562],
       [0.85885893, 0.598484  ]])

In [17]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0,10, size=(3, 3))

array([[8, 9, 9],
       [3, 7, 1],
       [1, 7, 8]])

More advanced type specification is possible, such as specifying big or little endian numbers; for more information, refer to the [NumPy documentation](http://numpy.org/).
NumPy also supports compound data types, which will be covered in [Structured Data: NumPy's Structured Arrays](02.09-Structured-Data-NumPy.ipynb).

## 2.0 Aritmética com NDarrays 

In [18]:
array_2 = np.array([2, 2, 2, 2, 2])
array_10 = np.array([10, 10, 10, 10, 10])

In [19]:
array_2+2

array([4, 4, 4, 4, 4])

In [20]:
array_2+array_10

array([12, 12, 12, 12, 12])

In [21]:
array_2*array_10

array([20, 20, 20, 20, 20])

In [22]:
array_10/array_2

array([5., 5., 5., 5., 5.])

In [23]:
array_10**array_2

array([100, 100, 100, 100, 100])

In [24]:
array_1a5 = np.array([1, 2, 3, 4, 5])

In [25]:
array_1a5**array_2

array([ 1,  4,  9, 16, 25])

In [26]:
array_1a5**2

array([ 1,  4,  9, 16, 25])

# Aula 7 - Indexação e Matrizes

## 1.0 Indexação básica, indexação booleana e fatiamento 

In [27]:
array_primos = np.array([2, 3, 5, 7, 11])
array_primos

array([ 2,  3,  5,  7, 11])

<img src="list-indexing.png">

https://github.com/jakevdp/WhirlwindTourOfPython/blob/master/fig/list-indexing.png

In [28]:
#vamos praticar com alguns exemplos de indexação básica
array_primos

array([ 2,  3,  5,  7, 11])

In [29]:
bool_lista = [True, False, True, True, False]
bool_lista

[True, False, True, True, False]

In [30]:
# boolean list
array_primos[bool_lista]

array([2, 5, 7])

In [31]:
#fatiamento
array_primos[2:4]

array([5, 7])

## 2.0 Matrizes

|  Dívida financeira | Renda familiar |
|:----:|:---|
| 1000 | 6000 |
| 2500 | 5500 |
| 3000 | 7000 |

In [32]:
matriz_3x2 = np.array([[1000,6000], [2500, 5500], [3000, 7000]])
matriz_3x2

array([[1000, 6000],
       [2500, 5500],
       [3000, 7000]])

In [33]:
matriz_3x2[:,1]/matriz_3x2[:,0]

array([6.        , 2.2       , 2.33333333])

___

# Aula 8 - Construindo e usando funções

## 1.0 Algumas funções nativas

Já utilizamos diversas funções nativas como: 

- A função **print()** que é útil para retornar resultados no output do *jupyter notebook*. 
- A função **len()** que retorna o tamanho de uma string ou lista.
- A função **type()** que retorna o tipo de dado.
- As funções **int(), float(), bool() e str()** retornam o argumento inserido na forma de um int, float, bool ou str, respectivamente.

### 1.1 A documentação do Python contém uma [lista](https://docs.python.org/pt-br/3/library/functions.html) de todas as funções nativas (built-in-functions).

## 2.0 Escrevendo uma função ``def``

Uma boa maneira de organizar, deixar mais legível e mais reutilizável os códigos em python é tornando-os uma função. Vamos cobrir esse tema agora e mostrar 2 maneiras de construir uma função.

### Fórmula IMC

$$IMC = \frac{PESO}{ALTURA*ALTURA}$$
Sendo peso em kg e a altura em metro


In [34]:
90/(1.90*1.90)

24.930747922437675

In [35]:
def calcula_IMC_lucas():
    return 90/(1.90*1.90)

In [36]:
calcula_IMC_lucas()

24.930747922437675

In [37]:
def calcula_IMC(peso,altura):
    imc = peso/(altura*altura)
    return imc

In [38]:
calcula_IMC(90,1.90)

24.930747922437675

- Muito abaixo do peso: 16 a 16,9 kg/m2
- Abaixo do peso: 17 a 18,4 kg/m2
- Peso normal: 18,5 a 24,9 kg/m2
- Acima do peso: 25 a 29,9 kg/m2

In [39]:
def calcula_IMC(peso,altura):
    imc = peso/(altura*altura)
    if imc < 17:
        print('Muito abaixo do peso')
    elif imc < 18.5:
        print('Abaixo do peso')
    elif imc < 25:
        print('Peso normal')
    else:
        print('Acima do peso')
    return imc

In [40]:
resultado_imc = calcula_IMC(90, 1.90)

Peso normal


In [41]:
resultado_imc

24.930747922437675

In [42]:
calcula_IMC(90, 1.90)

Peso normal


24.930747922437675

In [78]:
def calcula_IMC_com_default(peso=90, altura=1.90):
    imc = peso / (altura * altura)
    if imc < 17:
        print('Muito abaixo do peso')
    elif imc < 18.5:
        print('Abaixo do peso')
    elif imc < 25:
        print('Peso normal')
    else:
        print('Acima do peso')
    return imc

In [79]:
calcula_IMC_com_default(float(input("Qual é o seu peso(Kg) ?\n")),float(input("Qual é sua altura(m) ?\n")))

Qual é o seu peso(Kg) ?
64
Qual é sua altura(m) ?
1.69
Peso normal


22.40817898532965

## 3.0 Escrevendo uma função ``lambda``

In [80]:
calcula_imc_lambda = lambda peso, altura: peso/(altura*altura)
calcula_imc_lambda(90, 1.90)

24.930747922437675

**Equivalente à:**

In [46]:
def calcula_IMC_def(peso,altura):
    return peso/(altura*altura)
calcula_IMC_def(90, 1.90)

24.930747922437675

## 4.0 Métodos

Métodos são funções associadas à classe do objeto, e são chamadas como ```<nome_do_objeto>.<nome_do_método>```. Por exemplo, se você tem uma variável que contém um string chamada exemplo_texto, você pode chamar o método ```lower()``` da seguinte forma: ```exemplo_texto.lower()```


In [47]:
exemplo_texto = "R. Saturnino de Brito, 74"
exemplo_texto.lower()

'r. saturnino de brito, 74'

### 4.1 Métodos de *str*

Sendo ```meu_string```uma variável tipo string, todos os métodos abaixo são usados na forma ```meu_string.método()```. Alguns deles requerem ou têm como opcional um parâmetro dentro dos parêntesis, como o método ```meu_string.count('abc')```, que conta o número de ocorrências do string 'abc' dentro da variável ```meu_string```. 

Como os métodos e funções disponíveis são muitos, o aprendizado depende fortemente do contato e experiência com eles, então pratique sempre que tiver a oportunidade.


Observe que strings são dados **imutáveis**, isso significa que seu conteúdo não pode ser alterado sem construir uma variável completamente nova. Portanto, métodos de strings sempre retornam uma cópia da variável original alterada. Abaixo listamos alguns métodos de string que selecionamos:

- meu_string.**lower**(): retorna uma cópia de ```meu_string``` em letras minúsculas.
- meu_string.**upper**(): retorna uma cópia de ```meu_string``` em letras maiúsculas.
- meu_string.**capitalize**(): retorna uma cópia de ```meu_string``` com a primeira letra maiúscula.
- meu_string.**count**(substring): conta quantas vezes a sequencia ```substring``` aparece em ```meu_string```
- meu_string.**endswith**(sufixo): retorna um *boolean* conforme ```meu_string```inicia com a sequencia de ```sufixo```
- meu_string.**find**(): retorna a posição em que ```sub``` ocorre dentro de ```meu_string```. **Nota:** Se você quer verificar se ```sub``` ocorre dentro de ```meu_string```, utilize a construção ```sub in meu_string```.

**OBS:** Na [documentação do Python](https://docs.python.org/pt-br/3/library/stdtypes.html) você encontra todos os métodos de *str* nativos disponíveis. Além disso, haverão outros ainda que se mostrarão úteis e que serão carregados com pacotes específicos do Python.

In [48]:
meu_string = "Não são pedras"
meu_string.upper()

'NÃO SÃO PEDRAS'

In [49]:
meu_string = "Não são pedras"
meu_string.casefold()

'não são pedras'

In [50]:
meu_string = "Não são pedras"
meu_string.count('o')

2

# ATIVIDADE 2

Você tem duas strings: ```nome_campo``` e ```nome_cadastro```, uma delas veio através de um campo preenchido pelo usuário, e a outra veio de uma tabela cadastral do sistema. Escreva uma função que compara as duas retornando ```True``` caso sejam iguais e ```False```caso sejam diferentes, sem considerar diferenças de maiúsculas e minúsculas utilizando um dos métodos vistos.

In [51]:
def compara_nome(nome_campo, nome_sistema):
    pass

Tendo como input ```nome```, ```sobrenome``` e ```nome completo```, escreva duas funções que:
a) identifiquem se o nome e sobrenome estão contidos no nome completo
b) dado verdadeiro na anterior, retorne ```True``` se o nome completo está no formato de citação (sobrenome antes do nome) e ```False``` caso contrário.